write tests and make Checkbox component controlled
envoy/polarwind pull request #642
Opened 2022-01-11 01:13 UTC by knguyendh

- turned `Checkbox` component into a controlled component, ensuring that the checkbox can't be checked or unchecked regardless of passed props `checked`
- added tests to ensure proper checking behavior both in isolation and under a parent component `TestCheckboxComponent` that passes along a `checked` prop

2022-01-11 23:01 UTC, kamal requested changes

2022-01-11 23:01 UTC, kamal commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
shouldn't this be checked at this point?

indeterminate -- click -->  unchecked -- click --> checked

2022-01-11 23:01 UTC, kamal commented on src/components/Checkbox/tests/Checkbox.test.js
> +  test("remains unchecked when clicking the label of indeterminate select-all checkbox", () => {
i think these clicking on label tests have been established that it works in the isolated test above, so it isn't strictly necessary

2022-01-12 01:15 UTC, knguyendh commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
The indeterminate input checkbox HTML element natural behavior is interesting: https://stackoverflow.com/a/33529024

I'm not sure whether "_The first time you click on a checkbox that has its indeterminate set to true will simply change it to false and the checkbox will show its real state_" is true, because I haven't found official documentation that explicitly states this, but it is also the behavior I've been observing in this case; when `isDeterminate` is `true`, `isChanged` is false and gets passed to input element's `checked` attribute, so after the first click of a checkbox with its `indeterminate` prop set to `true`, `indeterminate` prop gets set to `false` and the checkbox's real `checked=false` state will be revealed. 

Thoughts? Since it's natural behavior, maybe it's better to keep it for the end users.

2022-01-12 01:20 UTC, knguyendh commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
Will modify the `TestingCheckboxComponent`'s `handleChange` function and how it passes the `checked` prop. With the way it's currently set up, I realized this indeterminate test is no different than the one in isolation.

2022-01-12 01:21 UTC, knguyendh commented on src/components/Checkbox/tests/Checkbox.test.js
> +  test("remains unchecked when clicking the label of indeterminate select-all checkbox", () => {
Removed

2022-01-12 21:41 UTC, knguyendh commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
Couldn't easily come up with a way for the `TestingCheckboxComponent` to start off with a `checked="indeterminate"` checkbox and then alternate between `true` and `false` `checked`, so I've removed this test.

2022-01-12 21:50 UTC, knguyendh commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
Was able to achieve this expected behavior by simply forcing it in `Checkbox`'s `handleOnChange`. Felt like a hack to me, but I checked out Shopify's [implementation](https://github.com/Shopify/polaris-react/blob/main/src/components/Checkbox/Checkbox.tsx#L133:L140), and I think they're forcing the indeterminate visual with `Icon` components.

2022-01-13 17:54 UTC, kamal commented on src/components/Checkbox/tests/Checkbox.test.js
> +    expect(screen.getByRole("checkbox")).not.toBeChecked();
You're right. Shopify doesn't use "real" indeterminate. Our styling for checkboxes relies on the pseudo-class `:indeterminate` which can only be set via JS. I looked at other implementations out there and saw that Reach UI makes use of the `value` prop to tell what state we are supposed to be in, instead of relying on what the DOM internal state says.

So I tweaked your implementation a little to follow this pattern.

2022-01-13 17:57 UTC, kamal approved these changes

2022-01-13 18:05 UTC, merged