DEVP-1390: Adds data-attribute support on Button links
envoy/polarwind pull request #834
Opened 2022-08-05 23:17 UTC by anthonyFloccari

2022-08-05 23:36 UTC, blindMoe commented
Thank you Anthony!

2022-08-05 23:37 UTC, blindMoe commented
We will need this on both the "button" and "link" options

2022-08-06 00:08 UTC, kamal requested changes

2022-08-06 00:08 UTC, kamal commented on src/components/Button/tests/Button.test.js
> +test("data-attributes get passed to link", () => {
can you test this for all 3 variations a button can be in?
1. a real `<button>` (Button with no `url` prop)
2. a disabled button (it becomes an `<a>` tag under the hood)
3. a Button with a `url` prop (it becomes an UnstyledLink)

2022-08-06 00:08 UTC, kamal commented on src/components/Button/tests/Button.test.js
> +    <Button data-thing="stuff" href="#">
can you test this with boolean data attributes too? they usually look like

```jsx
<Button data-modal-trigger>
  Open
</Button>
```

2022-08-06 00:08 UTC, kamal commented on src/components/Button/tests/Button.test.js
> +    <Button data-thing="stuff" href="#">
Curious what happens for malformed data attributes?

```jsx
<Button data-="what">
  Hello
</Button>
<Button data->
  Hello
</Button>
```

2022-08-08 19:15 UTC, anthonyFloccari commented on src/components/Button/tests/Button.test.js
> +    <Button data-thing="stuff" href="#">
It would be bad code style to use "data-" but it would technically be valid HTML that React handles just fine. I tried it out and data-="what" does set correctly on the element, and data- sets as a boolean attribute.

2022-08-08 19:15 UTC, anthonyFloccari commented on src/components/Button/tests/Button.test.js
> +    <Button data-thing="stuff" href="#">
Test added.

2022-08-08 19:16 UTC, anthonyFloccari commented on src/components/Button/tests/Button.test.js
> +test("data-attributes get passed to link", () => {
Cool, added those tests 👍

2022-08-08 20:51 UTC, kamal approved these changes

2022-08-08 21:18 UTC, merged